name = "worker"
compatibility_date = "2026-05-14"
main = "src/index.js"
workers_dev = true
upload_source_maps = true
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Non-secret vars
[vars]
APP_ENV = "development"


# Dev bindings
[[kv_namespaces]]
binding = "USERS"
id = "44288303b97a4a74a0084f3459473dc0"

[[kv_namespaces]]
binding = "REQUESTS"
id = "08b134041cdb422cb21df450e5447027"

[[kv_namespaces]]
binding = "RESET_TOKENS"
id = "83b083ca862145a588c578baf95db162"

[[kv_namespaces]]
binding = "FILE_META"
id = "f2a2044679d24024ac93395cc38faa1c"

# R2 Buckets
[[r2_buckets]]
binding = "personal_cloud_files"
bucket_name = "personal-cloud-files"


# Prodcution - deploys as separate worker
[env.production]
name = "worker-production"

[env.production.vars]
APP_ENV = "production"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "728c8c301e914652b7fefde939c6312f"

[[env.production.kv_namespaces]]
binding = "REQUESTS"
id = "e448678817c64a95bc021cd7f6f4fc9d"

[[env.production.kv_namespaces]]
binding = "RESET_TOKENS"
id = "daee8dd6dbf04bb789b23119a5d64f6c"

[[env.production.kv_namespaces]]
binding = "FILE_META"
id = "7c240098e5c349f9870e4a9013fc5b63"

# R2 Buckets
[[env.production.r2_buckets]]
binding = "personal_cloud_files"
bucket_name = "personal-cloud-files-prod"